(()=>{'use strict';
const VERSION='5.2.0';
const BOARDS={total:['🏆','総合','コレクション・交流・訪問を合算'],collection:['🪶','コレクション','種類・個体数・レア度から集計'],social:['🤝','交流','フレンド・訪問・交流回数から集計'],explorer:['🧭','おでかけ','訪問実績と直近7日の活動から集計']};
const S={board:'total',rank:null,busy:false,last:0};
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function hash(v){let h=2166136261;for(const c of String(v||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function pet(){const a=Array.isArray(G.petCollection)?G.petCollection:[];return a.find(x=>String(x.id)===String(G.activePetId))||a.find(x=>x.species===G.species)||{id:G.species,species:G.species,name:G.name,rarity:'N',rank:1}}
function rarity(p){return ['N','R','SR','SSR','UR'].includes(p?.rarity)?p.rarity:'N'}
function miniBird(p){const b=birds[p?.species]||birds.buncho_sakura,c=b.colors||birds.buncho_sakura.colors,r=rarity(p),h=hash(p?.id||p?.species),mark=h%3;return `<svg viewBox="0 0 88 88" class="v52-mini rarity-${r.toLowerCase()}" aria-hidden="true"><defs><linearGradient id="mb${h}" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${c.body}"/><stop offset="1" stop-color="${c.wing}"/></linearGradient></defs><ellipse cx="44" cy="78" rx="28" ry="5" fill="rgba(25,55,48,.12)"/><path d="M34 59 25 80 42 69 52 81 54 59Z" fill="${c.tail}"/><ellipse cx="44" cy="55" rx="25" ry="27" fill="url(#mb${h})"/><ellipse cx="44" cy="62" rx="15" ry="17" fill="${c.belly}"/><circle cx="44" cy="29" r="22" fill="${c.head}"/>${b.hasCheek?`<ellipse cx="27" cy="34" rx="8" ry="7" fill="${c.cheek}"/><ellipse cx="61" cy="34" rx="8" ry="7" fill="${c.cheek}"/>`:''}<circle cx="35" cy="27" r="5" fill="#111"/><circle cx="53" cy="27" r="5" fill="#111"/><circle cx="37" cy="25" r="1.8" fill="white"/><circle cx="55" cy="25" r="1.8" fill="white"/><path d="M35 40 Q44 34 53 40 Q44 49 35 40Z" fill="${c.beak}"/>${mark===1?`<path d="M31 55q13-8 26 0" fill="none" stroke="#fff" stroke-opacity=".18" stroke-width="3"/>`:''}<g class="mini-stars">${r==='UR'?'<text x="67" y="19">✦</text><text x="13" y="25">✦</text>':r==='SSR'?'<text x="67" y="20">✧</text>':''}</g></svg>`}
function decorateBird(){if(document.body.classList.contains('mofumori-v6'))return;const svg=$('#birdSvg');if(!svg||!svg.firstChild)return;const p=pet(),r=rarity(p),h=hash(p.id||p.species);svg.dataset.rarity=r.toLowerCase();svg.dataset.petSeed=String(h%4);const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.setAttribute('class',`v52-live-decor rarity-${r.toLowerCase()}`);let html='';if(r!=='N')html+=`<ellipse class="live-aura" cx="100" cy="196" rx="72" ry="15"/>`;if(r==='SR'||r==='SSR'||r==='UR')html+=`<g class="live-sparks"><text x="40" y="48">✦</text><text x="151" y="69">✧</text><text x="131" y="31">✦</text></g>`;if(r==='SSR')html+=`<path class="live-crown" d="M73 44 82 30 92 43 101 26 110 43 120 30 128 44"/>`;if(r==='UR')html+=`<ellipse class="live-ring" cx="100" cy="79" rx="50" ry="18"/>`;
 const kind=h%4;if(kind===0)html+=`<g class="live-accessory leaf"><path d="M63 113q14-12 27 1-14 11-27 4z"/><circle cx="64" cy="115" r="4"/></g>`;else if(kind===1)html+=`<g class="live-accessory ribbon"><path d="M77 115q23 13 46-1"/><path d="m98 121-12 14 15-4 13 5-7-16z"/></g>`;else if(kind===2)html+=`<g class="live-accessory charm"><circle cx="134" cy="54" r="7"/><path d="M134 41v26M121 54h26"/></g>`;else html+=`<g class="live-accessory collar"><path d="M74 117q26 13 52-1"/><circle cx="101" cy="125" r="6"/></g>`;
 g.innerHTML=html;svg.appendChild(g)}
function enhanceCards(root=document){$$('.pet-card',root).forEach(card=>{if(card.dataset.v52==='1')return;const id=card.dataset.p,p=(G.petCollection||[]).find(x=>String(x.id)===String(id));if(!p)return;card.dataset.v52='1';card.classList.add('v52-pet-card');const old=card.querySelector('.pet-icon');if(old){const wrap=document.createElement('span');wrap.className='v52-card-bird';wrap.innerHTML=miniBird(p);old.replaceWith(wrap)}});$$('.gacha-result',root).forEach((card,i)=>{if(card.dataset.v52==='1')return;card.dataset.v52='1';const results=card.querySelector('.result-icon');if(results){const species=(G.petCollection||[]).slice(-10)[i]?.species||G.species,p=(G.petCollection||[]).slice(-10)[i]||{id:`g${i}`,species,rarity:'N'};results.innerHTML=miniBird(p)}})}
function topbar(){if($('#v52Status'))return;const h=$('.header-content');if(!h)return;const x=document.createElement('div');x.id='v52Status';x.className='v52-status';x.innerHTML='<span id="v52PetCount">0 PETS</span><span id="v52FriendCount">0 FRIENDS</span><span id="v52RankChip">RANK --</span>';h.appendChild(x)}
function deck(){if($('#v52Deck'))return;const shell=$('.game-shell');if(!shell)return;const x=document.createElement('section');x.id='v52Deck';x.className='v52-deck';x.innerHTML=`<div class="v52-deck-copy"><small>YOUR FOREST TODAY</small><h1>小さな森を、毎日育てる。</h1><p>お世話・ガチャ・交流・ランキングがひとつにつながる育成ワールド。</p></div><div class="v52-deck-grid"><button data-tool="shop">🛍️<b>ショップ</b><small>ごはんと道具</small></button><button data-tool="inventory">🎒<b>持ち物</b><small>アイテム管理</small></button><button data-tool="minigame">🎮<b>ミニゲーム</b><small>遊んで育成</small></button><button data-tool="missions">✅<b>ミッション</b><small>今日の目標</small></button><button data-tool="chat">🧠<b>端末AI</b><small>ローカル会話</small></button><button data-tool="customize">✨<b>カスタム</b><small>森の設定</small></button></div>`;shell.parentNode.insertBefore(x,shell);$$('[data-tool]',x).forEach(b=>b.onclick=()=>{togglePanel(b.dataset.tool);setTimeout(()=>document.getElementById(`${b.dataset.tool}Panel`)?.scrollIntoView({behavior:'smooth',block:'start'}),30)})}
function nav(){if($('#v52Nav'))return;const n=document.createElement('nav');n.id='v52Nav';n.className='v52-nav';n.innerHTML='<button class="active" data-go="home">⌂<b>ホーム</b></button><button data-go="gacha">✦<b>ガチャ</b></button><button data-go="birds">🪶<b>仲間</b></button><button data-go="friends">♧<b>フレンド</b></button><button data-go="rank">♛<b>ランキング</b></button>';document.body.appendChild(n);$$('[data-go]',n).forEach(b=>b.onclick=()=>go(b.dataset.go))}
function go(k){$$('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===k));if(k==='home')return $('.game-shell')?.scrollIntoView({behavior:'smooth'});if(k==='gacha'||k==='birds'){showModal('birdModal');return setTimeout(()=>$(k==='gacha'?'#gachaHub':'#birdGrid')?.scrollIntoView({behavior:'smooth',block:'center'}),70)}openAccountHub();if(k==='friends')setSocialTab('friends');if(k==='rank'){setSocialTab('ranking');loadRank(S.board,true)}setTimeout(()=>$('#socialPanel')?.scrollIntoView({behavior:'smooth'}),60)}
function rankUi(){const tab=$('#socialRankingTab');if(!tab||$('#v52Ranking'))return;tab.innerHTML=`<section id="v52Ranking" class="v52-ranking"><header><div><small>SERVER VERIFIED</small><h3>リアルランキング</h3><p>端末の自己申告ではなく、サーバー上の個体・フレンド・訪問・交流記録から集計。</p></div><b class="v52-verified">✓ VERIFIED</b></header><div class="v52-board-tabs">${Object.entries(BOARDS).map(([k,v])=>`<button data-board="${k}" class="${k===S.board?'active':''}">${v[0]} ${v[1]}</button>`).join('')}</div><div id="v52RankInfo"></div><div id="v52Podium" class="v52-podium"></div><div id="v52RankList" class="v52-rank-list"></div><div id="v52Mine" class="v52-mine"></div></section>`;$$('[data-board]',tab).forEach(b=>b.onclick=()=>{S.board=b.dataset.board;$$('[data-board]').forEach(x=>x.classList.toggle('active',x===b));loadRank(S.board,true)})}
function metric(r){const m=r.metrics||{};if(S.board==='collection')return `${m.species||0}種 ・ ${m.pets||0}体 ・ レアP ${m.rarityPoints||0}`;if(S.board==='social')return `フレンド ${m.friends||0} ・ 交流 ${m.interactions||0}`;if(S.board==='explorer')return `訪問 ${m.visits||0} ・ 今週 ${m.weeklyVisits||0}`;return `${m.species||0}種 / ${m.friends||0}友 / ${m.visits||0}訪問`}
function rankAvatar(r){return miniBird({id:r.playerId,species:r.character?.species||'buncho_sakura',rarity:r.character?.rarity||'N',rank:r.character?.rank||1})}
function renderRank(d){S.rank=d;const rows=d?.rows||[],info=$('#v52RankInfo'),pod=$('#v52Podium'),list=$('#v52RankList'),mine=$('#v52Mine'),b=BOARDS[S.board];if(info)info.innerHTML=`<span>${b[0]}</span><div><b>${b[1]}ランキング</b><small>${b[2]}</small></div><button id="v52Refresh">↻ 更新</button>`;$('#v52Refresh')?.addEventListener('click',()=>loadRank(S.board,true),{once:true});if(pod)pod.innerHTML=rows.slice(0,3).map((r,i)=>`<article class="podium p${i+1} ${r.isMe?'me':''}"><em>${['🥇','🥈','🥉'][i]}</em><div>${rankAvatar(r)}</div><b>${esc(r.displayName||r.playerId)}</b><small>${esc(r.character?.name||'')}</small><strong>${Number(r.score||0).toLocaleString()} pt</strong></article>`).join('')||'<p class="rank-empty">まだ参加者がいません。</p>';if(list)list.innerHTML=rows.slice(3).map(r=>`<article class="rank-row ${r.isMe?'me':''}"><strong>#${r.position}</strong><div class="rank-avatar">${rankAvatar(r)}</div><div><b>${esc(r.displayName||r.playerId)}</b><small>${esc(metric(r))}</small></div><em>${Number(r.score||0).toLocaleString()}</em></article>`).join('');if(mine){if(d?.me){const r=d.me;mine.classList.add('show');mine.innerHTML=`<span><small>YOUR POSITION</small><b>#${r.position}</b></span><div class="rank-avatar">${rankAvatar(r)}</div><span><strong>${esc(r.displayName||'あなた')}</strong><small>${esc(metric(r))}</small></span><em>${Number(r.score||0).toLocaleString()} pt</em>`;$('#v52RankChip').textContent=`RANK #${r.position}`}else{mine.classList.remove('show');mine.innerHTML='';$('#v52RankChip').textContent='RANK --'}}}
async function loadRank(board='total',force=false){rankUi();if(S.busy)return;if(!force&&S.rank?.board===board&&Date.now()-S.last<30000)return renderRank(S.rank);S.busy=true;S.board=BOARDS[board]?board:'total';const list=$('#v52RankList');if(list)list.innerHTML='<div class="rank-loading"><i></i>サーバーで集計中…</div>';try{const r=await fetch(`/api/rankings?board=${encodeURIComponent(S.board)}&limit=100`,{headers:{Accept:'application/json'}}),j=await r.json().catch(()=>({}));if(r.status===401){if(list)list.innerHTML='<p class="rank-empty"><b>Googleログインで参加できます</b><br>ログインすると実データだけで順位を計算します。</p>';return}if(!r.ok)throw Error(j.message||`HTTP ${r.status}`);S.last=Date.now();renderRank(j.data)}catch(e){if(list)list.innerHTML=`<p class="rank-empty">ランキングを取得できませんでした<br>${esc(e.message)}</p>`}finally{S.busy=false}}
function confetti(){const root=$('#gachaReveal');if(!root)return;$$('.v52-confetti',root).forEach(x=>x.remove());for(let i=0;i<36;i++){const x=document.createElement('i');x.className='v52-confetti';x.style.cssText=`--x:${4+Math.random()*92}%;--d:${.8+Math.random()*1.5}s;--h:${Math.random()*360};--r:${Math.random()*360}deg`;root.appendChild(x)}}
function watch(){const grid=$('#birdGrid');if(grid&&!grid.dataset.v52){grid.dataset.v52='1';new MutationObserver(()=>enhanceCards(grid)).observe(grid,{childList:true,subtree:true})}const reveal=$('#gachaReveal');if(reveal&&!reveal.dataset.v52){reveal.dataset.v52='1';new MutationObserver(()=>{if(reveal.classList.contains('show')){confetti();setTimeout(()=>enhanceCards(reveal),650)}}).observe(reveal,{attributes:true,attributeFilter:['class']})}}
function chrome(){const p=pet(),r=rarity(p);let badge=$('#v52PetBadge');if(!badge){badge=document.createElement('div');badge.id='v52PetBadge';badge.className='v52-pet-badge';$('.habitat-toolbar')?.appendChild(badge)}if(badge)badge.innerHTML=`<span class="rarity-${r.toLowerCase()}">${r}</span><b>${esc(p.name||birds[p.species]?.name||'')}</b><small>個体ランク ${p.rank||1}</small>`;$('#v52PetCount').textContent=`${(G.petCollection||[]).length} PETS`;$('#v52FriendCount').textContent=`${socialState?.friends?.length||0} FRIENDS`;const f=$('.footer-stats small');if(f)f.textContent=`MOFUMORI v${VERSION}`}
function patch(){if(typeof renderBird==='function'&&!renderBird.__v52){const old=renderBird;const next=function(){old();decorateBird()};next.__v52=true;renderBird=next}if(typeof updateUI==='function'&&!updateUI.__v52){const old=updateUI;const next=function(){const z=old();chrome();enhanceCards();return z};next.__v52=true;updateUI=next}if(typeof setSocialTab==='function'&&!setSocialTab.__v52){const old=setSocialTab;const next=function(t){const z=old(t);if(t==='ranking'){rankUi();loadRank(S.board)}return z};next.__v52=true;setSocialTab=next}if(typeof showModal==='function'&&!showModal.__v52){const old=showModal;const next=function(id){const z=old(id);if(id==='birdModal')setTimeout(()=>enhanceCards($('#birdModal')),0);return z};next.__v52=true;showModal=next}}
function boot(){if(document.body.dataset.v52)return;document.body.dataset.v52='1';document.body.classList.add('mofumori-v52');topbar();deck();nav();rankUi();patch();watch();enhanceCards();decorateBird();chrome();$('#birdSvg')?.addEventListener('pointerdown',e=>{const el=e.currentTarget;el.classList.remove('v52-tap');void el.offsetWidth;el.classList.add('v52-tap');clearTimeout(el.__v52TapTimer);el.__v52TapTimer=setTimeout(()=>el.classList.remove('v52-tap'),700)});
$('#birdSvg')?.addEventListener('animationend',e=>{if(e.animationName==='v52Tap')e.currentTarget.classList.remove('v52-tap')});setInterval(()=>{patch();chrome();if($('#socialRankingTab')?.classList.contains('active'))loadRank(S.board)},30000)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,80),{once:true}):setTimeout(boot,80);
})();